### ISSUE TITLE
NeoVim: remark_ls not picking up requireConfig setting

### ISSUE THREAD

**Issue by kplattret** [remarkjs/remark-language-server#15]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-language-server@3.0.0

### Steps to reproduce

- `remark-language-server 3.0.0`
- `nodejs 18.20.2`
- `npm 10.5.0`

Add `remark_ls` to NeoVim using steps from the [README.md](https://github.com/remarkjs/remark-language-server?tab=readme-ov-file#neovim) (using `nvim-lspconfig`).

### Expected behavior

It should work out of the box and I should be able to set `requireConfig = true` without any issue.

### Actual behavior

I get the following error consistently, no matter what I try:

```
[ERROR][2024-07-27 20:08:20] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/kevin/.local/share/nvim/mason/bin/remark-language-server"	"stderr"	"file:///Users/kevin/.local/share/nvim/mason/packages/remark-language-server/node_modules/remark-language-server/node_modules/unified-language-server/lib/index.js:172\n          (raw) => ({requireConfig: Boolean(raw.requireConfig)})\n                                                ^\n\nTypeError: Cannot read properties of null (reading 'requireConfig')\n    at file:///Users/kevin/.local/share/nvim/mason/packages/remark-language-server/node_modules/remark-language-server/node_modules/unified-language-server/lib/index.js:172:49\n    at async file:///Users/kevin/.local/share/nvim/mason/packages/remark-language-server/node_modules/remark-language-server/node_modules/unified-language-server/lib/index.js:324:31\n    at async Promise.all (index 0)\n    at async processDocuments (file:///Users/kevin/.local/share/nvim/mason/packages/remark-language-server/node_modules/remark-language-server/node_modules/unified-language-server/lib/index.js:287:5)\n    at async checkDocuments (file:///Users/kevin/.local/share/nvim/mason/packages/remark-language-server/node_modules/remark-language-server/node_modules/unified-language-server/lib/index.js:362:19)\n\nNode.js v18.20.2\n"
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by remcohaszing** [comment]
The `requireConfig` option was added after the documentation for several editors. Personally I use Visual Studio code. The updated documentation for other editors could be slightly wrong. It uses the `requireConfig` setting from the `remark` section. You probably know what that means in NeoVim better than I do. :)

I’m guessing it should look something like this:

```lua
require'lspconfig'.remark_ls.setup {
  settings = {
    remark = {
      requireConfig = true
    }
  }
}
```

Or this:

```lua
require'lspconfig'.remark_ls.setup {
  settings = {
    'remark.requireConfig' = true
  }
}
```

**Comment by kplattret** [comment]
Thanks @remcohaszing, that first suggestion did the trick! 🙇

**Comment by remcohaszing** [comment]
I’m glad it works! ~~But which suggestion worked?~~ (The first, I didn’t read properly.) We need to update our documentation.
